Javascript sample PR
microsoftgraph/msgraph-training-javascriptspa pull request #34
Opened 2022-09-07 18:29 UTC by dodaromike

2022-09-07 19:06 UTC, jasonjoh requested changes
Please update the dependencies in index.html and test that it all still works. Also, we're missing config.example.js.

2022-09-07 19:06 UTC, jasonjoh commented on graph-tutorial/index.html
> +      <script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/moment.min.js"></script>
Update moment.js

```suggestion
      <script src="https://cdn.jsdelivr.net/npm/moment@2.29.4/moment.min.js"></script>
```

2022-09-07 19:06 UTC, jasonjoh commented on graph-tutorial/index.html
> +              crossorigin="anonymous"></script>
Please update

```suggestion
      <script src="https://alcdn.msauth.net/browser/2.28.1/js/msal-browser.min.js"
              integrity="sha384-ei8xVSyFPTuRnbO1sdYy5qJT6Kd9neBfVG8AjZySEwdMG1GhCThbceSqxJnx0Ci3"
              crossorigin="anonymous"></script>
```

2022-09-07 19:06 UTC, jasonjoh commented on graph-tutorial/index.html
> +      <script src="https://cdn.jsdelivr.net/npm/@microsoft/microsoft-graph-client@3.0.0/lib/graph-client-msalBrowserAuthProvider.js"></script>
Please update

```suggestion
      <script src="https://cdn.jsdelivr.net/npm/@microsoft/microsoft-graph-client@3.0.2/lib/graph-js-sdk.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@microsoft/microsoft-graph-client@3.0.2/lib/graph-client-msalBrowserAuthProvider.js"></script>
```

2022-09-07 22:28 UTC, dodaromike commented on README.md
> +## Configure the sample
Took out versions in microsoft-graph-client and npm/moment dependencies.  Without bootstrap@5.0.2 there are display problems.

2022-09-07 22:59 UTC, dodaromike commented on graph-tutorial/graph.js
> +function showCalendar(events) {
I committed some of your changes, and now I can't use any git commands from my local branch.  There is some kind of ownership problem:
C:\Users\v-dodaromike\ConvertSamples\JavaScriptSPA\msgraph-training-javascriptspa>git status
fatal: detected dubious ownership in repository at 'C:/Users/v-dodaromike/ConvertSamples/JavaScriptSPA/msgraph-training-javascriptspa'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/v-dodaromike/ConvertSamples/JavaScriptSPA/msgraph-training-javascriptspa

Set the environment variable GIT_TEST_DEBUG_UNSAFE_DIRECTORIES=true and run
again for more information.

2022-09-13 17:22 UTC, jasonjoh approved these changes

2022-09-13 17:24 UTC, merged